name: dnsmasqd
version: 2.76
summary: Network infrastructure swiss-army knife
description: |
  Dnsmasq provides network infrastructure for small networks: DNS, DHCP, router
  advertisement and network boot. It is designed to be lightweight and have a
  small footprint, suitable for resource constrained routers and firewalls. 
grade: stable
confinement: strict

apps:
  dnsmasq:
    command: bin/dnsmasq
    plugs:
      - network
      - network-bind
      - network-control
  dnsmasqd:
    daemon: simple
    command: bin/wrapper
    plugs:
      - network
      - network-bind
      - network-control

parts:
  dnsmasq:
    plugin: make
    source: https://github.com/lool/dnsmasq
    source-tag: v2.76
    organize:
      usr/local/sbin/dnsmasq: bin/dnsmasq
    snap:
      - bin/dnsmasq
  wrapper:
    plugin: dump
    source: .
    organize:
      wrapper: bin/wrapper
